# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name.ui1'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QDialog
from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
import control
import child


def SystemInformation():
    ui.label_2.setText("Powered by PyQt5, xx小组")


def openimage():
    imgName, imgType = QFileDialog.getOpenFileName(
        None, "打开图片", "", "*.jpg;;*.png;;All Files(*)")
    jpg = QtGui.QPixmap(imgName).scaled(480, 480)
    ui.label_3.setPixmap(jpg)

def trigger():
    Childwindow.show()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    Childwindow = QDialog()
    ui = control.Ui_MainWindow()
    Child_ui = child.Ui_Dialog()
    ui.setupUi(MainWindow)
    Child_ui.setupUi(Childwindow)
    MainWindow.show()
    ui.pushButton_2.clicked.connect(SystemInformation)
    ui.pushButton.clicked.connect(openimage)
    ui.pushButton_3.clicked.connect(trigger)
    sys.exit(app.exec_())
